### ISSUE TITLE
Scaffold survey data object

### ISSUE THREAD

**Issue by eemshi** [codefordenver/expunge-colorado-screener#9]
Don't need to flesh out question 6 or 8 at this time

**Comment by jdhern17** [comment]
just entered in PR for issue 9.

assumptions:
- kept skipToEnd by inertia, feel free to remove if we don't need.
- changed "Don't Know/Not Sure" to "Not Sure" due to the apostrophe in "Don't Know" making it harder. Feel free to update.
- later on, we will need to confirm with client regarding display of multiple questions per page.
- Made assumption that the display of the charge list question 6 will occur regardless of whether person was convicted or not. Question wording says "charge" not conviction to encapsulate both scenarios.

**Comment by jdhern17** [comment]
closing issue, first iteration done
